// <auto-generated />
using System;
using May.The.Fourth.Backend.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace may.the.fourth.backend.data.migrations
{
    [DbContext(typeof(StarWarsContext))]
    [Migration("20240428030958_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("May.The.Fourth.Backend.Data.Entities.FilmPlanetEntity", b =>
                {
                    b.Property<int>("PlanetId")
                        .HasColumnType("INT")
                        .HasColumnName("PlanetID");

                    b.HasKey("PlanetId");

                    b.ToTable("FilmsPlanets");

                    b.HasData(
                        new
                        {
                            PlanetId = 1
                        },
                        new
                        {
                            PlanetId = 2
                        },
                        new
                        {
                            PlanetId = 3
                        },
                        new
                        {
                            PlanetId = 4
                        },
                        new
                        {
                            PlanetId = 5
                        },
                        new
                        {
                            PlanetId = 6
                        },
                        new
                        {
                            PlanetId = 7
                        },
                        new
                        {
                            PlanetId = 8
                        },
                        new
                        {
                            PlanetId = 9
                        },
                        new
                        {
                            PlanetId = 10
                        });
                });

            modelBuilder.Entity("May.The.Fourth.Backend.Data.Entities.FilmeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("FilmeID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataLancamento")
                        .HasColumnType("DATE")
                        .HasColumnName("DataLancamento");

                    b.Property<string>("Diretor")
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("Diretor");

                    b.Property<int?>("Episodio")
                        .HasColumnType("INT")
                        .HasColumnName("Episodio");

                    b.Property<string>("Produtor")
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("Produtor");

                    b.Property<string>("TextoAbertura")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("TextoAbertura");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("Titulo");

                    b.HasKey("Id");

                    b.ToTable("Filmes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataLancamento = new DateTime(2028, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diretor = "Jana Doe",
                            Episodio = 10,
                            Produtor = "Leo Smith",
                            TextoAbertura = "After the fall of the Empire, the galaxy face",
                            Titulo = "The Rise of the Jedi"
                        },
                        new
                        {
                            Id = 2,
                            Titulo = "The Battle of the Stars"
                        },
                        new
                        {
                            Id = 3,
                            Titulo = "Return of the Light"
                        },
                        new
                        {
                            Id = 4,
                            Titulo = "Warriors of the Shadow Realm"
                        },
                        new
                        {
                            Id = 5,
                            Titulo = "The Galactic Quest"
                        },
                        new
                        {
                            Id = 6,
                            Titulo = "Rise of the Planetara"
                        },
                        new
                        {
                            Id = 7,
                            Titulo = "Echoes of the Stars"
                        },
                        new
                        {
                            Id = 8,
                            Titulo = "The Return of the Voyager"
                        },
                        new
                        {
                            Id = 9,
                            Titulo = "Voyager's Endgame"
                        },
                        new
                        {
                            Id = 10,
                            Titulo = "Galactic Odyssey"
                        },
                        new
                        {
                            Id = 11,
                            Titulo = "The Edge of the Universe"
                        });
                });

            modelBuilder.Entity("May.The.Fourth.Backend.Data.Entities.PlanetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("PlanetID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Climate")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("Climate");

                    b.Property<string>("Diameter")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)")
                        .HasColumnName("Diameter");

                    b.Property<string>("Gravity")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("Gravity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("Name");

                    b.Property<string>("OrbitalPeriod")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("OrbitalPeriod");

                    b.Property<string>("Population")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)")
                        .HasColumnName("Population");

                    b.Property<string>("RotationPeriod")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("RotationPeriod");

                    b.Property<string>("SurfaceWater")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("SurfaceWater");

                    b.Property<string>("Terrain")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("Terrain");

                    b.HasKey("Id");

                    b.ToTable("Planets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Climate = "arid",
                            Diameter = "10465",
                            Gravity = "1 standard",
                            Name = "Tatooine",
                            OrbitalPeriod = "304",
                            Population = "200000",
                            RotationPeriod = "23",
                            SurfaceWater = "1",
                            Terrain = "desert"
                        },
                        new
                        {
                            Id = 2,
                            Climate = "temperate",
                            Diameter = "12500",
                            Gravity = "1 standard",
                            Name = "Alderaan",
                            OrbitalPeriod = "364",
                            Population = "2000000000",
                            RotationPeriod = "24",
                            SurfaceWater = "40",
                            Terrain = "grasslands, mountains"
                        },
                        new
                        {
                            Id = 3,
                            Climate = "temperate, tropical",
                            Diameter = "10200",
                            Gravity = "1 standard",
                            Name = "Yavin IV",
                            OrbitalPeriod = "4818",
                            Population = "1000",
                            RotationPeriod = "24",
                            SurfaceWater = "8",
                            Terrain = "jungle, rainforests"
                        },
                        new
                        {
                            Id = 4,
                            Climate = "frozen",
                            Diameter = "7200",
                            Gravity = "1.1 standard",
                            Name = "Hoth",
                            OrbitalPeriod = "549",
                            Population = "unknown",
                            RotationPeriod = "23",
                            SurfaceWater = "100",
                            Terrain = "tundra, ice caves, mountain ranges"
                        },
                        new
                        {
                            Id = 5,
                            Climate = "murky",
                            Diameter = "8900",
                            Gravity = "N/A",
                            Name = "Dagobah",
                            OrbitalPeriod = "341",
                            Population = "unknown",
                            RotationPeriod = "23",
                            SurfaceWater = "8",
                            Terrain = "swamp, jungles"
                        },
                        new
                        {
                            Id = 6,
                            Climate = "temperate",
                            Diameter = "118000",
                            Gravity = "1.5 (surface), 1 standard (Cloud City)",
                            Name = "Bespin",
                            OrbitalPeriod = "5110",
                            Population = "6000000",
                            RotationPeriod = "12",
                            SurfaceWater = "0",
                            Terrain = "gas giant"
                        },
                        new
                        {
                            Id = 7,
                            Climate = "temperate",
                            Diameter = "4900",
                            Gravity = "0.85 standard",
                            Name = "Endor",
                            OrbitalPeriod = "402",
                            Population = "30000000",
                            RotationPeriod = "18",
                            SurfaceWater = "8",
                            Terrain = "forests, mountains, lakes"
                        },
                        new
                        {
                            Id = 8,
                            Climate = "temperate",
                            Diameter = "12120",
                            Gravity = "1 standard",
                            Name = "Naboo",
                            OrbitalPeriod = "312",
                            Population = "4500000000",
                            RotationPeriod = "26",
                            SurfaceWater = "12",
                            Terrain = "grassy hills, swamps, forests, mountains"
                        },
                        new
                        {
                            Id = 9,
                            Climate = "temperate",
                            Diameter = "12240",
                            Gravity = "1 standard",
                            Name = "Coruscant",
                            OrbitalPeriod = "368",
                            Population = "1000000000000",
                            RotationPeriod = "24",
                            SurfaceWater = "unknown",
                            Terrain = "cityscape, mountains"
                        },
                        new
                        {
                            Id = 10,
                            Climate = "temperate",
                            Diameter = "19720",
                            Gravity = "1 standard",
                            Name = "Kamino",
                            OrbitalPeriod = "463",
                            Population = "1000000000",
                            RotationPeriod = "27",
                            SurfaceWater = "100",
                            Terrain = "ocean"
                        });
                });

            modelBuilder.Entity("May.The.Fourth.Backend.Data.Entities.VehicleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("VehicleID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CargoCapacity")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CargoCapacity");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Class");

                    b.Property<string>("Consumables")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Consumables");

                    b.Property<string>("CostInCredits")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CostInCredits");

                    b.Property<string>("Crew")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Crew");

                    b.Property<string>("Length")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Length");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("Manufacturer");

                    b.Property<string>("MaxSpeed")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("MaxSpeed");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("Model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("Name");

                    b.Property<string>("Passengers")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Passengers");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            CargoCapacity = "50000",
                            Class = "wheeled",
                            Consumables = "2 months",
                            CostInCredits = "150000",
                            Crew = "46",
                            Length = "36.8",
                            Manufacturer = "Corellia Mining Corporation",
                            MaxSpeed = "30",
                            Model = "Digger Crawler",
                            Name = "Sand Crawler",
                            Passengers = "30"
                        },
                        new
                        {
                            Id = 6,
                            CargoCapacity = "50",
                            Class = "repulsorcraft",
                            Consumables = "0",
                            CostInCredits = "14500",
                            Crew = "1",
                            Length = "10.4",
                            Manufacturer = "Incom Corporation",
                            MaxSpeed = "1200",
                            Model = "T-16 skyhopper",
                            Name = "T-16 skyhopper",
                            Passengers = "1"
                        },
                        new
                        {
                            Id = 7,
                            CargoCapacity = "5",
                            Class = "repulsorcraft",
                            Consumables = "unknown",
                            CostInCredits = "10550",
                            Crew = "1",
                            Length = "3.4",
                            Manufacturer = "SoroSuub Corporation",
                            MaxSpeed = "250",
                            Model = "X-34 landspeeder",
                            Name = "X-34 landspeeder",
                            Passengers = "1"
                        },
                        new
                        {
                            Id = 8,
                            CargoCapacity = "65",
                            Class = "starfighter",
                            Consumables = "2 days",
                            CostInCredits = "unknown",
                            Crew = "1",
                            Length = "6.4",
                            Manufacturer = "Sienar Fleet Systems",
                            MaxSpeed = "1200",
                            Model = "Twin Ion Engine/Ln Starfighter",
                            Name = "TIE/LN starfighter",
                            Passengers = "0"
                        },
                        new
                        {
                            Id = 14,
                            CargoCapacity = "10",
                            Class = "airspeeder",
                            Consumables = "none",
                            CostInCredits = "unknown",
                            Crew = "2",
                            Length = "4.5",
                            Manufacturer = "Incom corporation",
                            MaxSpeed = "650",
                            Model = "t-47 airspeeder",
                            Name = "Snowspeeder",
                            Passengers = "0"
                        },
                        new
                        {
                            Id = 16,
                            CargoCapacity = "none",
                            Class = "space/planetary bomber",
                            Consumables = "2 days",
                            CostInCredits = "unknown",
                            Crew = "1",
                            Length = "7.8",
                            Manufacturer = "Sienar Fleet Systems",
                            MaxSpeed = "850",
                            Model = "TIE/sa bomber",
                            Name = "TIE bomber",
                            Passengers = "0"
                        },
                        new
                        {
                            Id = 18,
                            CargoCapacity = "1000",
                            Class = "assault walker",
                            Consumables = "unknown",
                            CostInCredits = "unknown",
                            Crew = "5",
                            Length = "20",
                            Manufacturer = "Kuat Drive Yards, Imperial Department of Military Research",
                            MaxSpeed = "60",
                            Model = "All Terrain Armored Transport",
                            Name = "AT-AT",
                            Passengers = "40"
                        },
                        new
                        {
                            Id = 19,
                            CargoCapacity = "200",
                            Class = "walker",
                            Consumables = "none",
                            CostInCredits = "unknown",
                            Crew = "2",
                            Length = "2",
                            Manufacturer = "Kuat Drive Yards, Imperial Department of Military Research",
                            MaxSpeed = "90",
                            Model = "All Terrain Scout Transport",
                            Name = "AT-ST",
                            Passengers = "0"
                        },
                        new
                        {
                            Id = 20,
                            CargoCapacity = "10",
                            Class = "repulsorcraft",
                            Consumables = "1 day",
                            CostInCredits = "75000",
                            Crew = "2",
                            Length = "7",
                            Manufacturer = "Bespin Motors",
                            MaxSpeed = "1500",
                            Model = "Storm IV Twin-Pod",
                            Name = "Storm IV Twin-Pod cloud car",
                            Passengers = "0"
                        },
                        new
                        {
                            Id = 24,
                            CargoCapacity = "2000000",
                            Class = "sail barge",
                            Consumables = "Live food tanks",
                            CostInCredits = "285000",
                            Crew = "26",
                            Length = "30",
                            Manufacturer = "Ubrikkian Industries Custom Vehicle Division",
                            MaxSpeed = "100",
                            Model = "Modified Luxury Sail Barge",
                            Name = "Sail barge",
                            Passengers = "500"
                        });
                });

            modelBuilder.Entity("May.The.Fourth.Backend.Data.Entities.FilmPlanetEntity", b =>
                {
                    b.HasOne("May.The.Fourth.Backend.Data.Entities.PlanetEntity", "Planet")
                        .WithMany("FilmPlanet")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planet");
                });

            modelBuilder.Entity("May.The.Fourth.Backend.Data.Entities.PlanetEntity", b =>
                {
                    b.Navigation("FilmPlanet");
                });
#pragma warning restore 612, 618
        }
    }
}
